/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TenantSlugIndexRouteImport } from './routes/$tenantSlug/index'
import { Route as AuthenticatedWhatsappRouteImport } from './routes/_authenticated.whatsapp'
import { Route as AuthenticatedTrackingRouteImport } from './routes/_authenticated.tracking'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated.relatorios'
import { Route as AuthenticatedMapaRouteImport } from './routes/_authenticated.mapa'
import { Route as AuthenticatedKdsRouteImport } from './routes/_authenticated.kds'
import { Route as AuthenticatedKanbanRouteImport } from './routes/_authenticated.kanban'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated.financeiro'
import { Route as AuthenticatedEntregadorRouteImport } from './routes/_authenticated.entregador'
import { Route as AuthenticatedConfigsRouteImport } from './routes/_authenticated.configs'
import { Route as AuthenticatedCentralRouteImport } from './routes/_authenticated.central'
import { Route as AuthenticatedCardapioRouteImport } from './routes/_authenticated.cardapio'
import { Route as AuthenticatedAutomacoesRouteImport } from './routes/_authenticated.automacoes'
import { Route as AuthenticatedAuditoriaRouteImport } from './routes/_authenticated.auditoria'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated.analytics'
import { Route as TenantSlugCheckoutRouteImport } from './routes/$tenantSlug/checkout'
import { Route as TenantSlugCarrinhoRouteImport } from './routes/$tenantSlug/carrinho'
import { Route as RastreioOrderIdTokenRouteImport } from './routes/rastreio.$orderId.$token'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantSlugIndexRoute = TenantSlugIndexRouteImport.update({
  id: '/$tenantSlug/',
  path: '/$tenantSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWhatsappRoute = AuthenticatedWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTrackingRoute = AuthenticatedTrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMapaRoute = AuthenticatedMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKdsRoute = AuthenticatedKdsRouteImport.update({
  id: '/kds',
  path: '/kds',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKanbanRoute = AuthenticatedKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEntregadorRoute = AuthenticatedEntregadorRouteImport.update({
  id: '/entregador',
  path: '/entregador',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfigsRoute = AuthenticatedConfigsRouteImport.update({
  id: '/configs',
  path: '/configs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCentralRoute = AuthenticatedCentralRouteImport.update({
  id: '/central',
  path: '/central',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCardapioRoute = AuthenticatedCardapioRouteImport.update({
  id: '/cardapio',
  path: '/cardapio',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAutomacoesRoute = AuthenticatedAutomacoesRouteImport.update({
  id: '/automacoes',
  path: '/automacoes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditoriaRoute = AuthenticatedAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const TenantSlugCheckoutRoute = TenantSlugCheckoutRouteImport.update({
  id: '/$tenantSlug/checkout',
  path: '/$tenantSlug/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantSlugCarrinhoRoute = TenantSlugCarrinhoRouteImport.update({
  id: '/$tenantSlug/carrinho',
  path: '/$tenantSlug/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const RastreioOrderIdTokenRoute = RastreioOrderIdTokenRouteImport.update({
  id: '/rastreio/$orderId/$token',
  path: '/rastreio/$orderId/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/$tenantSlug/carrinho': typeof TenantSlugCarrinhoRoute
  '/$tenantSlug/checkout': typeof TenantSlugCheckoutRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/automacoes': typeof AuthenticatedAutomacoesRoute
  '/cardapio': typeof AuthenticatedCardapioRoute
  '/central': typeof AuthenticatedCentralRoute
  '/configs': typeof AuthenticatedConfigsRoute
  '/entregador': typeof AuthenticatedEntregadorRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/kanban': typeof AuthenticatedKanbanRoute
  '/kds': typeof AuthenticatedKdsRoute
  '/mapa': typeof AuthenticatedMapaRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/tracking': typeof AuthenticatedTrackingRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/$tenantSlug/': typeof TenantSlugIndexRoute
  '/rastreio/$orderId/$token': typeof RastreioOrderIdTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/$tenantSlug/carrinho': typeof TenantSlugCarrinhoRoute
  '/$tenantSlug/checkout': typeof TenantSlugCheckoutRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/automacoes': typeof AuthenticatedAutomacoesRoute
  '/cardapio': typeof AuthenticatedCardapioRoute
  '/central': typeof AuthenticatedCentralRoute
  '/configs': typeof AuthenticatedConfigsRoute
  '/entregador': typeof AuthenticatedEntregadorRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/kanban': typeof AuthenticatedKanbanRoute
  '/kds': typeof AuthenticatedKdsRoute
  '/mapa': typeof AuthenticatedMapaRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/tracking': typeof AuthenticatedTrackingRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/$tenantSlug': typeof TenantSlugIndexRoute
  '/rastreio/$orderId/$token': typeof RastreioOrderIdTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/$tenantSlug/carrinho': typeof TenantSlugCarrinhoRoute
  '/$tenantSlug/checkout': typeof TenantSlugCheckoutRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/auditoria': typeof AuthenticatedAuditoriaRoute
  '/_authenticated/automacoes': typeof AuthenticatedAutomacoesRoute
  '/_authenticated/cardapio': typeof AuthenticatedCardapioRoute
  '/_authenticated/central': typeof AuthenticatedCentralRoute
  '/_authenticated/configs': typeof AuthenticatedConfigsRoute
  '/_authenticated/entregador': typeof AuthenticatedEntregadorRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/kanban': typeof AuthenticatedKanbanRoute
  '/_authenticated/kds': typeof AuthenticatedKdsRoute
  '/_authenticated/mapa': typeof AuthenticatedMapaRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/tracking': typeof AuthenticatedTrackingRoute
  '/_authenticated/whatsapp': typeof AuthenticatedWhatsappRoute
  '/$tenantSlug/': typeof TenantSlugIndexRoute
  '/rastreio/$orderId/$token': typeof RastreioOrderIdTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/$tenantSlug/carrinho'
    | '/$tenantSlug/checkout'
    | '/analytics'
    | '/auditoria'
    | '/automacoes'
    | '/cardapio'
    | '/central'
    | '/configs'
    | '/entregador'
    | '/financeiro'
    | '/kanban'
    | '/kds'
    | '/mapa'
    | '/relatorios'
    | '/tracking'
    | '/whatsapp'
    | '/$tenantSlug/'
    | '/rastreio/$orderId/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/$tenantSlug/carrinho'
    | '/$tenantSlug/checkout'
    | '/analytics'
    | '/auditoria'
    | '/automacoes'
    | '/cardapio'
    | '/central'
    | '/configs'
    | '/entregador'
    | '/financeiro'
    | '/kanban'
    | '/kds'
    | '/mapa'
    | '/relatorios'
    | '/tracking'
    | '/whatsapp'
    | '/$tenantSlug'
    | '/rastreio/$orderId/$token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/$tenantSlug/carrinho'
    | '/$tenantSlug/checkout'
    | '/_authenticated/analytics'
    | '/_authenticated/auditoria'
    | '/_authenticated/automacoes'
    | '/_authenticated/cardapio'
    | '/_authenticated/central'
    | '/_authenticated/configs'
    | '/_authenticated/entregador'
    | '/_authenticated/financeiro'
    | '/_authenticated/kanban'
    | '/_authenticated/kds'
    | '/_authenticated/mapa'
    | '/_authenticated/relatorios'
    | '/_authenticated/tracking'
    | '/_authenticated/whatsapp'
    | '/$tenantSlug/'
    | '/rastreio/$orderId/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  TenantSlugCarrinhoRoute: typeof TenantSlugCarrinhoRoute
  TenantSlugCheckoutRoute: typeof TenantSlugCheckoutRoute
  TenantSlugIndexRoute: typeof TenantSlugIndexRoute
  RastreioOrderIdTokenRoute: typeof RastreioOrderIdTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tenantSlug/': {
      id: '/$tenantSlug/'
      path: '/$tenantSlug'
      fullPath: '/$tenantSlug/'
      preLoaderRoute: typeof TenantSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/whatsapp': {
      id: '/_authenticated/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AuthenticatedWhatsappRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tracking': {
      id: '/_authenticated/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof AuthenticatedTrackingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mapa': {
      id: '/_authenticated/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof AuthenticatedMapaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/kds': {
      id: '/_authenticated/kds'
      path: '/kds'
      fullPath: '/kds'
      preLoaderRoute: typeof AuthenticatedKdsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/kanban': {
      id: '/_authenticated/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof AuthenticatedKanbanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/entregador': {
      id: '/_authenticated/entregador'
      path: '/entregador'
      fullPath: '/entregador'
      preLoaderRoute: typeof AuthenticatedEntregadorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configs': {
      id: '/_authenticated/configs'
      path: '/configs'
      fullPath: '/configs'
      preLoaderRoute: typeof AuthenticatedConfigsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/central': {
      id: '/_authenticated/central'
      path: '/central'
      fullPath: '/central'
      preLoaderRoute: typeof AuthenticatedCentralRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cardapio': {
      id: '/_authenticated/cardapio'
      path: '/cardapio'
      fullPath: '/cardapio'
      preLoaderRoute: typeof AuthenticatedCardapioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/automacoes': {
      id: '/_authenticated/automacoes'
      path: '/automacoes'
      fullPath: '/automacoes'
      preLoaderRoute: typeof AuthenticatedAutomacoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/auditoria': {
      id: '/_authenticated/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuthenticatedAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/$tenantSlug/checkout': {
      id: '/$tenantSlug/checkout'
      path: '/$tenantSlug/checkout'
      fullPath: '/$tenantSlug/checkout'
      preLoaderRoute: typeof TenantSlugCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tenantSlug/carrinho': {
      id: '/$tenantSlug/carrinho'
      path: '/$tenantSlug/carrinho'
      fullPath: '/$tenantSlug/carrinho'
      preLoaderRoute: typeof TenantSlugCarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rastreio/$orderId/$token': {
      id: '/rastreio/$orderId/$token'
      path: '/rastreio/$orderId/$token'
      fullPath: '/rastreio/$orderId/$token'
      preLoaderRoute: typeof RastreioOrderIdTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedAuditoriaRoute: typeof AuthenticatedAuditoriaRoute
  AuthenticatedAutomacoesRoute: typeof AuthenticatedAutomacoesRoute
  AuthenticatedCardapioRoute: typeof AuthenticatedCardapioRoute
  AuthenticatedCentralRoute: typeof AuthenticatedCentralRoute
  AuthenticatedConfigsRoute: typeof AuthenticatedConfigsRoute
  AuthenticatedEntregadorRoute: typeof AuthenticatedEntregadorRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedKanbanRoute: typeof AuthenticatedKanbanRoute
  AuthenticatedKdsRoute: typeof AuthenticatedKdsRoute
  AuthenticatedMapaRoute: typeof AuthenticatedMapaRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedTrackingRoute: typeof AuthenticatedTrackingRoute
  AuthenticatedWhatsappRoute: typeof AuthenticatedWhatsappRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedAuditoriaRoute: AuthenticatedAuditoriaRoute,
  AuthenticatedAutomacoesRoute: AuthenticatedAutomacoesRoute,
  AuthenticatedCardapioRoute: AuthenticatedCardapioRoute,
  AuthenticatedCentralRoute: AuthenticatedCentralRoute,
  AuthenticatedConfigsRoute: AuthenticatedConfigsRoute,
  AuthenticatedEntregadorRoute: AuthenticatedEntregadorRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedKanbanRoute: AuthenticatedKanbanRoute,
  AuthenticatedKdsRoute: AuthenticatedKdsRoute,
  AuthenticatedMapaRoute: AuthenticatedMapaRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedTrackingRoute: AuthenticatedTrackingRoute,
  AuthenticatedWhatsappRoute: AuthenticatedWhatsappRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  TenantSlugCarrinhoRoute: TenantSlugCarrinhoRoute,
  TenantSlugCheckoutRoute: TenantSlugCheckoutRoute,
  TenantSlugIndexRoute: TenantSlugIndexRoute,
  RastreioOrderIdTokenRoute: RastreioOrderIdTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
